version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27000:27017'
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: sneaker_shop

volumes:
  mongo_data:
